trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: 'build'
    jobs:
      - job: 'build the code' 
      steps:
        - task: 'Maven@3'
          inputs:
            mavenPomFile: pom.xml
            goals: 'package'
            publishJUnitResults: true
            testResultFiles: '**/surefire-reports/*.xml'
